server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaber
          uri: https://github.com/renzodamian/microserviceLGV2
          search-paths: config-data
  application:
    name: config-service
